### ISSUE TITLE
Mobile support 

### ISSUE THREAD

**Issue by bjorndm** [kanryu/mado#1]
Thanks for writing this library! It would be great if we could also add mobile support. Thanks for considering it.

**Comment by kanryu** [comment]
@bjorndm Thank you for your suggestion. This is a mobile support request.

yes. gioui, which mado is based on, supports both Android and iOS, so in principle it is possible.
However, I am not aware of any mobile support for glfw.
I checked the source code, and it seems that Android and iOS compatibility is basically not taken into consideration.

Mado's initial purpose is to address some of the needs of existing GLFW, in other words, to be a good alternative to GLFW. I don't think Android or iOS are included.

**Comment by bjorndm** [comment]
Well, I think now Ebitengine uses a fork of gomobile. So strictly it isn't needed that mado supports mobile platforms, but we could also include gomobile under one API to make mado even more portable. But I should probably make pull requests if I want this.

**Comment by kkoreilly** [comment]
Given that glfw does not support mobile and IME support on mobile is automatic through the virtual keyboard, I do not believe that mado should support it. It is not really possible to implement glfw APIs on mobile, which is the stated purpose of the mado project. A unified API encompassing both desktop and mobile is possible (see https://github.com/cogentcore/core/tree/main/goosi for my implementation), but that would be a much different API than glfw, which is why they do not plan to support it and mado should not either. I am happy to do a PR removing the gio mobile code currently present.

**Comment by kanryu** [comment]
@kkoreilly  The proposal is reasonable! :)
and it is also flawed.

In other words, as an alternative to glfw, it is reasonable to remove features that glfw does not support as a means of narrowing down the purpose of development.
The ultimate goal of mado is for its own API to become a base library for other Go GUI projects.

In other words, mado and mado/glfw are two sets of APIs provided in parallel.

However, as you are well aware, there are still many issues remaining in the practical implementation of mado/glfw, and we will not be able to begin developing the mado API until these are completed. I think it is a reasonable decision to leave the current commit as a branch as mado-mobile and remove the Android/iOS source code.

**Comment by kanryu** [comment]
I made it.

**Comment by kkoreilly** [comment]
Yep, I agree that we should add mobile support once we develop the mado API, but not right now while we focus on glfw.
