### ISSUE TITLE
The glfw package doesn't compile on Linux

### ISSUE THREAD

**Issue by bjorndm** [kanryu/mado#5]
The GLFW package doesn't compile on Linux. Maybe I should focus on this first.

```shell
go build ./glfw
go: downloading golang.org/x/exp/shiny v0.0.0-20220906200021-fcb1a314c389
# github.com/kanryu/mado/app
app/glfwconfig.go:143:11: undefined: PlatformContextState
app/glfwconfig.go:167:18: undefined: PlatformLibraryContextState
app/egl_x11.go:29:10: cannot use &x11Context{…} (value of type *x11Context) as mado.Context value in return statement: *x11Context does not implement mado.Context (missing method SwapBuffers)
app/vulkan_wayland.go:50:10: cannot use c (variable of type *wlVkContext) as mado.Context value in return statement: *wlVkContext does not implement mado.Context (missing method SwapBuffers)
app/vulkan_x11.go:50:10: cannot use c (variable of type *x11VkContext) as mado.Context value in return statement: *x11VkContext does not implement mado.Context (missing method SwapBuffers)
app/egl_wayland.go:42:10: cannot use &wlContext{…} (value of type *wlContext) as mado.Context value in return statement: *wlContext does not implement mado.Context (missing method SwapBuffers)
app/os_wayland.go:268:17: cannot use w (variable of type *window) as mado.Driver value in argument to w.w.SetDriver: *window does not implement mado.Driver (missing method GetFrameBufferSize)
app/os_x11.go:841:17: cannot use w (variable of type *x11Window) as mado.Driver value in argument to w.w.SetDriver: *x11Window does not implement mado.Driver (missing method GetFrameBufferSize)
```

**Comment by bjorndm** [comment]
By the way is there a reason to add these SwapBuffers() functions, and how are the different from Present() ?

**Comment by bjorndm** [comment]
And also, sorry to say it, but it seems to me that using these types, PlatformContext and PlatformContextState make portability even harder. Normally, I think these functions should be added in the internal/gl package or in the app/internal/platform package.

**Comment by bjorndm** [comment]
I made a draft #6, but Wayland really is annoying. I'd almost think arcan is better.

**Comment by kanryu** [comment]
Thanks for trying to get mado to actually work on Linux! :)
Actually, I was also thinking of modifying the same part.

mado first tested its ability to accurately dispatch Window events on Windows, Mac, and Linux, and at that time also tested its functionality on Linux.

After that, I started implementing glfw and put Linux on the back burner. SwapBuffers etc. are glfw's most important APIs.

So I'll take the pull request you posted earlier, but ultimately I need glfw's compatibility to work on Linux.

**Comment by kkoreilly** [comment]
Mado also doesn't compile on macOS with some similar errors:

```
# github.com/kanryu/mado/app
../../../../go/pkg/mod/github.com/kanryu/mado@v0.0.0-20240312025633-5ee50a6fe211/app/glfwconfig.go:143:11: undefined: PlatformContextState
../../../../go/pkg/mod/github.com/kanryu/mado@v0.0.0-20240312025633-5ee50a6fe211/app/glfwconfig.go:167:18: undefined: PlatformLibraryContextState
```

**Comment by kkoreilly** [comment]
The reason it doesn't compile on macOS is the metal driver; one major thing that we need to figure out is how we are going to structure support for different graphics drivers. My GUI framework, Cogent Core, currently only supports Vulkan, which provides the highest performance and functionality, but does not work on some systems. If we can figure out some way to support falling back on OpenGL and Metal after first trying Vulkan, that would be great. In the meantime, I filed #7 so that mado at least compiles on macOS without any build tags.

**Comment by kanryu** [comment]
@kkoreilly Thank you for pointing that out. I was aware of the problem in advance, and the workaround is as described in the README FAQ.

Apart from that, there is room to consider which of the app.window (native window of each OS) and XXXcontext(glContext, d3d11Context mtlContext) implemented in the current mado should be supported and which should be left.

For example, the original gioui had an implementation of the OpenGL ES backend for Windows, which is cryptic to the average Windows user. Because desktop Windows doesn't provide OpenGL ES. In the end I scrapped this implementation and reimplemented a new OpenGL layer for Windows.

**Comment by kkoreilly** [comment]
Yep, I saw the note in the README, but I think it is still nicer for it to compile without build tags. It seems good to support Vulkan and OpenGL on all platforms and Metal on macOS. Also, are you still planning to get rid of the gio GUI code, or are you keeping it for testing purposes? I hope to get Cogent Core at least minimally working with mado tomorrow after I fix some Vulkan issues, so that should serve as a good testing platform.

**Comment by kanryu** [comment]
@kkoreilly Proposed Thank you. :)

I've looked at the glfw source code, and it looks like vulkan's initialization routines exist independently of those for OpenGL, and are designed to run on basically any OS as calling glfwVulkanSupported()

On the other hand, Metal is implemented to be checked as an extension in the OpenGL initialization routine on MacOS, and it appears to be designed to switch the surface of VK_EXT_metal_surface VK_MVK_macos_surface as a result of querying the hardware.

These discussions are constructive, but are not related to the original issue, so please post a new issue.

**Comment by kanryu** [comment]
We are currently verifying that it works on Linux, but since we can at least build it, we will mark it as supported and close it.
